import {chromium} from 'playwright';
import {getConsumerDefinition,isLoginUrl} from './runtime.mjs';
import {focusPauseAndFill} from './prompt-input.mjs';

const providerIndex=process.argv.indexOf('--provider'),definition=getConsumerDefinition(providerIndex>=0?process.argv[providerIndex+1]:'');
const endpointIndex=process.argv.indexOf('--endpoint'),endpoint=endpointIndex>=0?process.argv[endpointIndex+1]:`http://127.0.0.1:${definition.port}`;
const parsedEndpoint=new URL(endpoint||'invalid:');
if(parsedEndpoint.protocol!=='http:'||!['127.0.0.1','localhost'].includes(parsedEndpoint.hostname)||!/^[0-9]+$/.test(parsedEndpoint.port)||Number(parsedEndpoint.port)<1||Number(parsedEndpoint.port)>65535)throw new Error(`${definition.displayName} CDP endpoint must be loopback HTTP with an explicit valid port.`);
const sendButton='button[type="submit"],button[aria-label*="Send" i],[data-testid="send-button"]',stopButton='button[aria-label*="Stop" i],[data-testid="stop-button"],button[title*="Stop" i]';
const result=(value,isError=false)=>({content:[{type:'text',text:JSON.stringify(value)}],...(isError?{isError:true}:{})});let browser,page,queue=Promise.resolve();
async function connect(){if(!browser||!browser.isConnected())browser=await chromium.connectOverCDP(endpoint);const context=browser.contexts()[0];if(!context)throw new Error(`The dedicated ${definition.displayName} browser is not running.`);if(!page||page.isClosed())page=await context.newPage();return page;}
async function closePage(){try{if(page&&!page.isClosed())await page.close();}catch{}page=undefined;}
async function ready(target){await target.goto(definition.url,{waitUntil:'domcontentloaded',timeout:30000});if(isLoginUrl(definition,target.url()))throw new Error(`${definition.displayName} is not signed in. Run Setup and sign in in the dedicated browser.`);await target.waitForSelector(definition.inputSelector,{state:'visible',timeout:15000});if(definition.signedOutSelector&&await target.locator(definition.signedOutSelector).first().isVisible().catch(()=>false))throw new Error(`${definition.displayName} is not signed in in the attached browser profile.`);}
async function responseState(target){const items=await target.$$(definition.responseSelector);return {count:items.length,text:items.length?(await items.at(-1).innerText().catch(()=>''))?.trim()||'':''};}
async function enableHighThinking(target){const controls=target.locator(definition.highThinkingSelector);for(let index=0;index<await controls.count();index++){const control=controls.nth(index);if(!await control.isVisible().catch(()=>false)||!await control.isEnabled().catch(()=>false))continue;const pressed=await control.getAttribute('aria-pressed'),state=await control.getAttribute('data-state');if(pressed==='true'||state==='on'||state==='checked')return;await control.click();return;}throw new Error(`${definition.displayName} high-thinking control is unavailable for this account or current page. OmniRoute should try another provider.`);}
async function stable(target,before){let last='',same=0;const started=Date.now();while(Date.now()-started<120000){await target.waitForTimeout(750);const current=await responseState(target),changed=current.count>before.count||(current.text&&current.text!==before.text);if(!changed)continue;if(current.text===last)same++;else{last=current.text;same=0;}const generating=Boolean(await target.$(stopButton));if(last&&!generating&&same>=3)return last;}return last;}
async function submit(target,prompt){await focusPauseAndFill(target,definition.inputSelector,prompt);const button=await target.$(sendButton);if(button&&await button.isVisible()&&await button.isEnabled())await button.click();else await target.keyboard.press('Enter');}
async function invoke(name,args={}){try{const target=await connect();await ready(target);if(name==='test_connection')return result({status:'ready',browser:'dedicated-chromium-cdp',endpoint});if(name!==definition.toolName)return result({error:`Unknown tool: ${name}`},true);const prompt=typeof args.prompt==='string'?args.prompt.trim():'';if(!prompt)return result({error:'prompt must be a non-empty string'},true);if(args.highThinking===true)await enableHighThinking(target);const before=await responseState(target);await submit(target,prompt);const output=await stable(target,before);if(!output)throw new Error(`${definition.displayName} returned no readable response.`);return result({output,usage:{model:definition.modelId,estimatedTokens:Math.ceil((prompt.length+output.length)/4)},metadata:{transport:'browser-cdp',privateLocalOnly:true,highThinking:args.highThinking===true,timestamp:new Date().toISOString()}});}catch(error){return result({error:error instanceof Error?error.message:String(error)},true);}finally{await closePage();}}
function call(name,args){const task=queue.then(()=>invoke(name,args));queue=task.then(()=>undefined,()=>undefined);return task;}
function send(id,payload){process.stdout.write(`${JSON.stringify({jsonrpc:'2.0',id,...payload})}\n`);}let buffered='';process.stdin.setEncoding('utf8');process.stdin.on('data',chunk=>{buffered+=chunk;for(;;){const newline=buffered.indexOf('\n');if(newline<0)break;const line=buffered.slice(0,newline).trim();buffered=buffered.slice(newline+1);if(!line)continue;void(async()=>{try{const message=JSON.parse(line);if(message.id===undefined)return;if(message.method==='initialize')send(message.id,{result:{protocolVersion:'2025-03-26',capabilities:{tools:{}},serverInfo:{name:`${definition.id}-consumer-adapter`,version:'0.1.0-private.1'}}});else if(message.method==='tools/list')send(message.id,{result:{tools:[{name:definition.toolName,description:`Ask ${definition.displayName} through the signed-in local browser session.`,inputSchema:{type:'object',properties:{prompt:{type:'string',minLength:1},highThinking:{type:'boolean',description:'Enable the site high-thinking control before submitting.'}},required:['prompt'],additionalProperties:false}},{name:'test_connection',description:`Check the attached ${definition.displayName} browser login.`,inputSchema:{type:'object',properties:{},additionalProperties:false}}]}});else if(message.method==='tools/call')send(message.id,{result:await call(message.params?.name,message.params?.arguments)});else send(message.id,{error:{code:-32601,message:'Method not found'}});}catch(error){try{const parsed=JSON.parse(line);if(parsed.id!==undefined)send(parsed.id,{error:{code:-32603,message:error instanceof Error?error.message:String(error)}});}catch{}}})();}});
